### ISSUE TITLE
Game Crush

### ISSUE THREAD

**Issue by beta010507** [not-navyblue/UnHax#3]
Good am/pm while playing the game with unhax mod their seem to be a crush when i trained a unit, not civilian unit but military units whilst having the unhax buildings i hope you could read this and fix the issue I don't know if it's just my device but you or maybe everyone using this mod. anyway love your mods keep up the good work.

**Comment by not-navyblue** [comment]
can you give a save file where the game crashed while playing with unhax?

**Comment by beta010507** [comment]
Can i send it to you via discord? 
Discord Name:meme19
I'm using windows 64 unciv for the save file 
game version: 3.18.5

**Comment by not-navyblue** [comment]
fixed in v1.16b
